// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: vod/business/vod_upload.proto

package business

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VodUrlUploadURLSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceUrl    string `protobuf:"bytes,1,opt,name=SourceUrl,proto3" json:"SourceUrl,omitempty"`       // 视频的URL
	CallbackArgs string `protobuf:"bytes,2,opt,name=CallbackArgs,proto3" json:"CallbackArgs,omitempty"` // 透传的回调信息
	Md5          string `protobuf:"bytes,3,opt,name=Md5,proto3" json:"Md5,omitempty"`                   // 视频的MD5
	TemplateId   string `protobuf:"bytes,4,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`     // 模板Id
	Title        string `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`               // 标题
	Description  string `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`   // 描述信息
	Tags         string `protobuf:"bytes,7,opt,name=Tags,proto3" json:"Tags,omitempty"`                 // 标签
	Category     string `protobuf:"bytes,8,opt,name=Category,proto3" json:"Category,omitempty"`         // 分类
}

func (x *VodUrlUploadURLSet) Reset() {
	*x = VodUrlUploadURLSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VodUrlUploadURLSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodUrlUploadURLSet) ProtoMessage() {}

func (x *VodUrlUploadURLSet) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodUrlUploadURLSet.ProtoReflect.Descriptor instead.
func (*VodUrlUploadURLSet) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{0}
}

func (x *VodUrlUploadURLSet) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *VodUrlUploadURLSet) GetCallbackArgs() string {
	if x != nil {
		return x.CallbackArgs
	}
	return ""
}

func (x *VodUrlUploadURLSet) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *VodUrlUploadURLSet) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *VodUrlUploadURLSet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VodUrlUploadURLSet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VodUrlUploadURLSet) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *VodUrlUploadURLSet) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type VodURLSets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URLSets []*VodUrlUploadURLSet `protobuf:"bytes,1,rep,name=URLSets,proto3" json:"URLSets,omitempty"`
}

func (x *VodURLSets) Reset() {
	*x = VodURLSets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VodURLSets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodURLSets) ProtoMessage() {}

func (x *VodURLSets) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodURLSets.ProtoReflect.Descriptor instead.
func (*VodURLSets) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{1}
}

func (x *VodURLSets) GetURLSets() []*VodUrlUploadURLSet {
	if x != nil {
		return x.URLSets
	}
	return nil
}

type VodUrlResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ValuePair `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *VodUrlResponseData) Reset() {
	*x = VodUrlResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VodUrlResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodUrlResponseData) ProtoMessage() {}

func (x *VodUrlResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodUrlResponseData.ProtoReflect.Descriptor instead.
func (*VodUrlResponseData) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{2}
}

func (x *VodUrlResponseData) GetData() []*ValuePair {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValuePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId     string `protobuf:"bytes,1,opt,name=JobId,proto3" json:"JobId,omitempty"`         // Url对应的JobId
	SourceUrl string `protobuf:"bytes,2,opt,name=SourceUrl,proto3" json:"SourceUrl,omitempty"` // 上传的Url
}

func (x *ValuePair) Reset() {
	*x = ValuePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuePair) ProtoMessage() {}

func (x *ValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuePair.ProtoReflect.Descriptor instead.
func (*ValuePair) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{3}
}

func (x *ValuePair) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ValuePair) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

// {"SpaceName":"your space name", "URLSets":"{\"URLSets\":[{\"SourceUrl\":\"url\"}]}"}
// {"SpaceName":"your space name", "URLSets":"[{\"SourceUrl\":\"url\"}]"}
type QueryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *QueryUploadResult `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *QueryData) Reset() {
	*x = QueryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryData) ProtoMessage() {}

func (x *QueryData) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryData.ProtoReflect.Descriptor instead.
func (*QueryData) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{4}
}

func (x *QueryData) GetData() *QueryUploadResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryUploadResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoInfoList  []*URLSet `protobuf:"bytes,1,rep,name=VideoInfoList,proto3" json:"VideoInfoList,omitempty"`
	NotExistJobIds []string  `protobuf:"bytes,2,rep,name=NotExistJobIds,proto3" json:"NotExistJobIds,omitempty"`
}

func (x *QueryUploadResult) Reset() {
	*x = QueryUploadResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUploadResult) ProtoMessage() {}

func (x *QueryUploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUploadResult.ProtoReflect.Descriptor instead.
func (*QueryUploadResult) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUploadResult) GetVideoInfoList() []*URLSet {
	if x != nil {
		return x.VideoInfoList
	}
	return nil
}

func (x *QueryUploadResult) GetNotExistJobIds() []string {
	if x != nil {
		return x.NotExistJobIds
	}
	return nil
}

type CommitData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CommitUploadInfoResponse `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CommitData) Reset() {
	*x = CommitData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitData) ProtoMessage() {}

func (x *CommitData) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitData.ProtoReflect.Descriptor instead.
func (*CommitData) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{6}
}

func (x *CommitData) GetData() *CommitUploadInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommitUploadInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid          string         `protobuf:"bytes,1,opt,name=Vid,proto3" json:"Vid,omitempty"`
	SourceInfo   *VodSourceInfo `protobuf:"bytes,2,opt,name=SourceInfo,proto3" json:"SourceInfo,omitempty"`
	PosterUri    string         `protobuf:"bytes,3,opt,name=PosterUri,proto3" json:"PosterUri,omitempty"`
	CallbackArgs string         `protobuf:"bytes,4,opt,name=CallbackArgs,proto3" json:"CallbackArgs,omitempty"`
}

func (x *CommitUploadInfoResponse) Reset() {
	*x = CommitUploadInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitUploadInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadInfoResponse) ProtoMessage() {}

func (x *CommitUploadInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadInfoResponse.ProtoReflect.Descriptor instead.
func (*CommitUploadInfoResponse) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{7}
}

func (x *CommitUploadInfoResponse) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *CommitUploadInfoResponse) GetSourceInfo() *VodSourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *CommitUploadInfoResponse) GetPosterUri() string {
	if x != nil {
		return x.PosterUri
	}
	return ""
}

func (x *CommitUploadInfoResponse) GetCallbackArgs() string {
	if x != nil {
		return x.CallbackArgs
	}
	return ""
}

type URLSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId  string         `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	JobId      string         `protobuf:"bytes,2,opt,name=JobId,proto3" json:"JobId,omitempty"`
	SourceUrl  string         `protobuf:"bytes,3,opt,name=SourceUrl,proto3" json:"SourceUrl,omitempty"`
	State      string         `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Vid        string         `protobuf:"bytes,5,opt,name=Vid,proto3" json:"Vid,omitempty"`
	SpaceName  string         `protobuf:"bytes,6,opt,name=SpaceName,proto3" json:"SpaceName,omitempty"`
	AccountId  string         `protobuf:"bytes,7,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	SourceInfo *VodSourceInfo `protobuf:"bytes,8,opt,name=SourceInfo,proto3" json:"SourceInfo,omitempty"`
}

func (x *URLSet) Reset() {
	*x = URLSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLSet) ProtoMessage() {}

func (x *URLSet) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLSet.ProtoReflect.Descriptor instead.
func (*URLSet) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{8}
}

func (x *URLSet) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *URLSet) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *URLSet) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *URLSet) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *URLSet) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *URLSet) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

func (x *URLSet) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *URLSet) GetSourceInfo() *VodSourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

type ApplyUploadInfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ApplyUploadInfoData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *ApplyUploadInfoResult) Reset() {
	*x = ApplyUploadInfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyUploadInfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyUploadInfoResult) ProtoMessage() {}

func (x *ApplyUploadInfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyUploadInfoResult.ProtoReflect.Descriptor instead.
func (*ApplyUploadInfoResult) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyUploadInfoResult) GetData() *ApplyUploadInfoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApplyUploadInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadAddress *UploadAddress `protobuf:"bytes,1,opt,name=UploadAddress,proto3" json:"UploadAddress,omitempty"`
}

func (x *ApplyUploadInfoData) Reset() {
	*x = ApplyUploadInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyUploadInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyUploadInfoData) ProtoMessage() {}

func (x *ApplyUploadInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyUploadInfoData.ProtoReflect.Descriptor instead.
func (*ApplyUploadInfoData) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyUploadInfoData) GetUploadAddress() *UploadAddress {
	if x != nil {
		return x.UploadAddress
	}
	return nil
}

type UploadAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreInfos   []*StoreInfo  `protobuf:"bytes,1,rep,name=StoreInfos,proto3" json:"StoreInfos,omitempty"`
	UploadHosts  []string      `protobuf:"bytes,2,rep,name=UploadHosts,proto3" json:"UploadHosts,omitempty"`
	UploadHeader []*HeaderPair `protobuf:"bytes,3,rep,name=UploadHeader,proto3" json:"UploadHeader,omitempty"`
	SessionKey   string        `protobuf:"bytes,4,opt,name=SessionKey,proto3" json:"SessionKey,omitempty"`
}

func (x *UploadAddress) Reset() {
	*x = UploadAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAddress) ProtoMessage() {}

func (x *UploadAddress) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAddress.ProtoReflect.Descriptor instead.
func (*UploadAddress) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{11}
}

func (x *UploadAddress) GetStoreInfos() []*StoreInfo {
	if x != nil {
		return x.StoreInfos
	}
	return nil
}

func (x *UploadAddress) GetUploadHosts() []string {
	if x != nil {
		return x.UploadHosts
	}
	return nil
}

func (x *UploadAddress) GetUploadHeader() []*HeaderPair {
	if x != nil {
		return x.UploadHeader
	}
	return nil
}

func (x *UploadAddress) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type StoreInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreUri string `protobuf:"bytes,1,opt,name=StoreUri,proto3" json:"StoreUri,omitempty"`
	Auth     string `protobuf:"bytes,2,opt,name=Auth,proto3" json:"Auth,omitempty"`
}

func (x *StoreInfo) Reset() {
	*x = StoreInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInfo) ProtoMessage() {}

func (x *StoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInfo.ProtoReflect.Descriptor instead.
func (*StoreInfo) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{12}
}

func (x *StoreInfo) GetStoreUri() string {
	if x != nil {
		return x.StoreUri
	}
	return ""
}

func (x *StoreInfo) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type HeaderPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *HeaderPair) Reset() {
	*x = HeaderPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderPair) ProtoMessage() {}

func (x *HeaderPair) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderPair.ProtoReflect.Descriptor instead.
func (*HeaderPair) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{13}
}

func (x *HeaderPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CommitUploadInfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CommitUploadInfoData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *CommitUploadInfoResult) Reset() {
	*x = CommitUploadInfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitUploadInfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadInfoResult) ProtoMessage() {}

func (x *CommitUploadInfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadInfoResult.ProtoReflect.Descriptor instead.
func (*CommitUploadInfoResult) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{14}
}

func (x *CommitUploadInfoResult) GetData() *CommitUploadInfoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommitUploadInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid        string         `protobuf:"bytes,1,opt,name=Vid,proto3" json:"Vid,omitempty"`
	PosterUri  string         `protobuf:"bytes,2,opt,name=PosterUri,proto3" json:"PosterUri,omitempty"`
	SourceInfo *VodSourceInfo `protobuf:"bytes,3,opt,name=SourceInfo,proto3" json:"SourceInfo,omitempty"`
}

func (x *CommitUploadInfoData) Reset() {
	*x = CommitUploadInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vod_business_vod_upload_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitUploadInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadInfoData) ProtoMessage() {}

func (x *CommitUploadInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_vod_business_vod_upload_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadInfoData.ProtoReflect.Descriptor instead.
func (*CommitUploadInfoData) Descriptor() ([]byte, []int) {
	return file_vod_business_vod_upload_proto_rawDescGZIP(), []int{15}
}

func (x *CommitUploadInfoData) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *CommitUploadInfoData) GetPosterUri() string {
	if x != nil {
		return x.PosterUri
	}
	return ""
}

func (x *CommitUploadInfoData) GetSourceInfo() *VodSourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

var File_vod_business_vod_upload_proto protoreflect.FileDescriptor

var file_vod_business_vod_upload_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x76, 0x6f, 0x64, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2f, 0x76,
	0x6f, 0x64, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56,
	0x6f, 0x64, 0x1a, 0x1d, 0x76, 0x6f, 0x64, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x2f, 0x76, 0x6f, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x12, 0x56, 0x6f, 0x64, 0x55, 0x72, 0x6c, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x64,
	0x35, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x64, 0x35, 0x12, 0x1e, 0x0a, 0x0a,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x22, 0x4d, 0x0a, 0x0a, 0x56, 0x6f, 0x64, 0x55, 0x52, 0x4c, 0x53, 0x65,
	0x74, 0x73, 0x12, 0x3f, 0x0a, 0x07, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x56, 0x6f, 0x64, 0x55, 0x72, 0x6c, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x52, 0x07, 0x55, 0x52, 0x4c, 0x53,
	0x65, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x56, 0x6f, 0x64, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x09, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x45, 0x0a, 0x09,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x7c, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x56, 0x6f, 0x64, 0x2e, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x52, 0x0d, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x4e, 0x6f, 0x74,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0e, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x49, 0x64,
	0x73, 0x22, 0x4d, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x3f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f,
	0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0xb0, 0x01, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x56, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x69, 0x64, 0x12,
	0x40, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x56, 0x6f, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x69, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x69, 0x12,
	0x22, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41,
	0x72, 0x67, 0x73, 0x22, 0x80, 0x02, 0x0a, 0x06, 0x55, 0x52, 0x4c, 0x53, 0x65, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4a, 0x6f, 0x62,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x56, 0x6f, 0x64,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x53, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x3a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f,
	0x64, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x13, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x46, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x56, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0d, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xd2, 0x01, 0x0a, 0x0d, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3c, 0x0a, 0x0a,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x0c,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x22,
	0x3b, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x75, 0x74, 0x68, 0x22, 0x34, 0x0a, 0x0a,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x55, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3b, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x56, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x88, 0x01, 0x0a, 0x14, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x56, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55,
	0x72, 0x69, 0x12, 0x40, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x56, 0x6f, 0x64, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0xaf, 0x01, 0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x79, 0x74,
	0x65, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x76, 0x6f, 0x64, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x09, 0x56, 0x6f,
	0x64, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x01, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x54, 0x76, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x6f, 0x64, 0x2f, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0xa0, 0x01, 0x01, 0xd8, 0x01, 0x01, 0xc2, 0x02, 0x00, 0xca, 0x02, 0x1a,
	0x56, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x5c, 0x56, 0x6f,
	0x64, 0x5c, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0xe2, 0x02, 0x19, 0x56, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vod_business_vod_upload_proto_rawDescOnce sync.Once
	file_vod_business_vod_upload_proto_rawDescData = file_vod_business_vod_upload_proto_rawDesc
)

func file_vod_business_vod_upload_proto_rawDescGZIP() []byte {
	file_vod_business_vod_upload_proto_rawDescOnce.Do(func() {
		file_vod_business_vod_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_vod_business_vod_upload_proto_rawDescData)
	})
	return file_vod_business_vod_upload_proto_rawDescData
}

var file_vod_business_vod_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_vod_business_vod_upload_proto_goTypes = []interface{}{
	(*VodUrlUploadURLSet)(nil),       // 0: Vcloud.Models.Vod.VodUrlUploadURLSet
	(*VodURLSets)(nil),               // 1: Vcloud.Models.Vod.VodURLSets
	(*VodUrlResponseData)(nil),       // 2: Vcloud.Models.Vod.VodUrlResponseData
	(*ValuePair)(nil),                // 3: Vcloud.Models.Vod.ValuePair
	(*QueryData)(nil),                // 4: Vcloud.Models.Vod.QueryData
	(*QueryUploadResult)(nil),        // 5: Vcloud.Models.Vod.QueryUploadResult
	(*CommitData)(nil),               // 6: Vcloud.Models.Vod.CommitData
	(*CommitUploadInfoResponse)(nil), // 7: Vcloud.Models.Vod.CommitUploadInfoResponse
	(*URLSet)(nil),                   // 8: Vcloud.Models.Vod.URLSet
	(*ApplyUploadInfoResult)(nil),    // 9: Vcloud.Models.Vod.ApplyUploadInfoResult
	(*ApplyUploadInfoData)(nil),      // 10: Vcloud.Models.Vod.ApplyUploadInfoData
	(*UploadAddress)(nil),            // 11: Vcloud.Models.Vod.UploadAddress
	(*StoreInfo)(nil),                // 12: Vcloud.Models.Vod.StoreInfo
	(*HeaderPair)(nil),               // 13: Vcloud.Models.Vod.HeaderPair
	(*CommitUploadInfoResult)(nil),   // 14: Vcloud.Models.Vod.CommitUploadInfoResult
	(*CommitUploadInfoData)(nil),     // 15: Vcloud.Models.Vod.CommitUploadInfoData
	(*VodSourceInfo)(nil),            // 16: Vcloud.Models.Vod.VodSourceInfo
}
var file_vod_business_vod_upload_proto_depIdxs = []int32{
	0,  // 0: Vcloud.Models.Vod.VodURLSets.URLSets:type_name -> Vcloud.Models.Vod.VodUrlUploadURLSet
	3,  // 1: Vcloud.Models.Vod.VodUrlResponseData.Data:type_name -> Vcloud.Models.Vod.ValuePair
	5,  // 2: Vcloud.Models.Vod.QueryData.Data:type_name -> Vcloud.Models.Vod.QueryUploadResult
	8,  // 3: Vcloud.Models.Vod.QueryUploadResult.VideoInfoList:type_name -> Vcloud.Models.Vod.URLSet
	7,  // 4: Vcloud.Models.Vod.CommitData.Data:type_name -> Vcloud.Models.Vod.CommitUploadInfoResponse
	16, // 5: Vcloud.Models.Vod.CommitUploadInfoResponse.SourceInfo:type_name -> Vcloud.Models.Vod.VodSourceInfo
	16, // 6: Vcloud.Models.Vod.URLSet.SourceInfo:type_name -> Vcloud.Models.Vod.VodSourceInfo
	10, // 7: Vcloud.Models.Vod.ApplyUploadInfoResult.Data:type_name -> Vcloud.Models.Vod.ApplyUploadInfoData
	11, // 8: Vcloud.Models.Vod.ApplyUploadInfoData.UploadAddress:type_name -> Vcloud.Models.Vod.UploadAddress
	12, // 9: Vcloud.Models.Vod.UploadAddress.StoreInfos:type_name -> Vcloud.Models.Vod.StoreInfo
	13, // 10: Vcloud.Models.Vod.UploadAddress.UploadHeader:type_name -> Vcloud.Models.Vod.HeaderPair
	15, // 11: Vcloud.Models.Vod.CommitUploadInfoResult.Data:type_name -> Vcloud.Models.Vod.CommitUploadInfoData
	16, // 12: Vcloud.Models.Vod.CommitUploadInfoData.SourceInfo:type_name -> Vcloud.Models.Vod.VodSourceInfo
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_vod_business_vod_upload_proto_init() }
func file_vod_business_vod_upload_proto_init() {
	if File_vod_business_vod_upload_proto != nil {
		return
	}
	file_vod_business_vod_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vod_business_vod_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VodUrlUploadURLSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VodURLSets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VodUrlResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValuePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUploadResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitUploadInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyUploadInfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyUploadInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitUploadInfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vod_business_vod_upload_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitUploadInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vod_business_vod_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vod_business_vod_upload_proto_goTypes,
		DependencyIndexes: file_vod_business_vod_upload_proto_depIdxs,
		MessageInfos:      file_vod_business_vod_upload_proto_msgTypes,
	}.Build()
	File_vod_business_vod_upload_proto = out.File
	file_vod_business_vod_upload_proto_rawDesc = nil
	file_vod_business_vod_upload_proto_goTypes = nil
	file_vod_business_vod_upload_proto_depIdxs = nil
}
